---
# Adapted from https://eksctl.io/usage/creating-and-managing-clusters/
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: antfield-cluster
  region: eu-west-1

vpc:
  subnets:
    private:
      eu-west-1a: { id: subnet-0ff156e0c4a6d300c }
      eu-west-1b: { id: subnet-0549cdab573695c03 }
      eu-west-1c: { id: subnet-0426fb4a607393184 }

addons:
  - name: vpc-cni
    version: stable
    attachPolicy:
      Statement:
        - Effect: Allow
          Action:
            - ec2:AssignPrivateIpAddresses
            - ec2:AttachNetworkInterface
            - ec2:CreateNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DescribeInstances
            - ec2:DescribeTags
            - ec2:DescribeNetworkInterfaces
            - ec2:DescribeInstanceTypes
            - ec2:DetachNetworkInterface
            - ec2:ModifyNetworkInterfaceAttribute
            - ec2:UnassignPrivateIpAddresses
          Resource: '*'
  # https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html#add-ons-aws-ebs-csi-driver
  - name: aws-ebs-csi-driver
    version: stable
    # https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/example-iam-policy.json
    attachPolicy:
      Statement:
        - Effect: Allow
          Action:
            - ec2:CreateSnapshot
            - ec2:AttachVolume
            - ec2:DetachVolume
            - ec2:ModifyVolume
            - ec2:DescribeAvailabilityZones
            - ec2:DescribeInstances
            - ec2:DescribeSnapshots
            - ec2:DescribeTags
            - ec2:DescribeVolumes
            - ec2:DescribeVolumesModifications
          Resource: "*"
        - "Effect": "Allow"
          "Action":
            - "ec2:CreateTags"
          "Resource":
            - "arn:aws:ec2:*:*:volume/*"
            - "arn:aws:ec2:*:*:snapshot/*"
          "Condition":
            "StringEquals":
              "ec2:CreateAction":
                - "CreateVolume"
                - "CreateSnapshot"
        - "Effect": "Allow"
          "Action":[ec2:DeleteTags]
          "Resource":[arn:aws:ec2:*:*:volume/*, arn:aws:ec2:*:*:snapshot/*]
        - "Effect": "Allow"
          "Action": [ec2:CreateVolume]
          "Resource": "*"
          "Condition":
            "StringLike":
              "aws:RequestTag/ebs.csi.aws.com/cluster": "true"
        - "Effect": "Allow",
          "Action":
            - "ec2:CreateVolume"
          "Resource": "*",
          "Condition":
            "StringLike":
              "aws:RequestTag/CSIVolumeName": "*"
        - "Effect": "Allow"
          "Action": ["ec2:DeleteVolume"]
          "Resource": "*"
          "Condition":
            "StringLike":
              "ec2:ResourceTag/ebs.csi.aws.com/cluster": "true"
        - "Effect": "Allow",
          "Action": ["ec2:DeleteVolume"]
          "Resource": "*"
          "Condition":
            "StringLike":
              "ec2:ResourceTag/CSIVolumeName": "*"
        - "Effect": "Allow"
          "Action": ["ec2:DeleteVolume"]
          "Resource": "*"
          "Condition":
            "StringLike":
              "ec2:ResourceTag/kubernetes.io/created-for/pvc/name": "*"
        - "Effect": "Allow"
          "Action": ["ec2:DeleteSnapshot"]
          "Resource": "*"
          "Condition":
            "StringLike":
              "ec2:ResourceTag/CSIVolumeSnapshotName": "*"
        - "Effect": "Allow"
          "Action": ["ec2:DeleteSnapshot"]
          "Resource": "*"
          "Condition":
            "StringLike":
              "ec2:ResourceTag/ebs.csi.aws.com/cluster": "true"

managedNodeGroups:
  - name: service-pool-1
    labels:
      role: workers
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
  - name: machine-learning-pool-1
    labels:
      role: ml
    instanceType: m5.2xlarge
    desiredCapacity: 2
    privateNetworking: true
